# 服务配置
server:
  name: "hertz-template"
  host: "0.0.0.0"
  port: 9988
  mode: "debug" # debug, release
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# 数据库配置
database:
  enabled: false # 设置为false以在开发环境中禁用数据库
  driver: "mysql"
  host: "118.178.196.149"
  port: 3306
  username: "root"
  password: "kTICUG4OV3XKLvCb"
  database: "hertz_template"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600s
  log_level: "info" # silent, error, warn, info

# Redis配置
redis:
  enabled: false # 设置为false以在开发环境中禁用Redis
  host: "118.178.196.149"
  port: 6379
  password: "kTICUG4OV3XKLvCb"
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s

# JWT配置
jwt:
  secret: "your-secret-key-change-in-production"
  expire_time: 24h
  refresh_expire_time: 168h # 7 days
  issuer: "hertz-template"

# 日志配置
log:
  level: "info" # debug, info, warn, error, fatal
  stdout: true # stdout, stderr, file
  file_name: "./logs/app.log"
  max_size: 100 # MB
  max_backups: 10
  max_age: 3 # days
  compress: true


# 监控配置
monitoring:
  enabled: true
  prometheus:
    enabled: true
    path: "/metrics"
    port: 9090
  pprof:
    enabled: true
    path: "/debug/pprof"

# 分布式追踪配置
tracing:
  enabled: true
  jaeger:
    service_name: "hertz-template"
    agent_host: "localhost"
    agent_port: 6831
    sampler_type: "const"
    sampler_param: 1.0
    log_spans: true
    local_agent_host_port: "localhost:6831"

# 分页配置
pagination:
  default_page: 1
  default_page_size: 20
  max_page_size: 100

# 限流配置
rate_limit:
  enabled: true
  requests_per_second: 100
  burst: 200

# CORS配置
cors:
  enabled: true
  allow_origins:
    - "*"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  expose_headers:
    - "Content-Length"
  allow_credentials: true
  max_age: 12h